CREATE TABLE buku (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_kategori int,
    judul_buku text,
    no_buku int,
    penerbit text,
    pengarang text,
    tahun_terbit date,
    tgl_upload date,
    gambar text
)

CREATE TABLE peminjaman (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_peminjam text,
    tgl_pinjam date,
    tgl_pengembalian date
)

CREATE TABLE detail_peminjaman (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_peminjaman int,
    id_buku int,
    jumlah int
)

CREATE TABLE detail_peminjaman_temp (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_buku int,
    jumlah int
)